(function () {
  const STORAGE_KEY='ETHRION_LANG';
  const DICT={
    en:{"nav.home":"Home","nav.about":"About","nav.lab":"Lab","nav.projects":"Projects","nav.insights":"Insights","nav.connect":"Connect",
        "hero.title":"ETHRION — Human × AI Co‑evolution","hero.subtitle":"Neon Flow · Co‑evolution Orb · Pulse Grid",
        "cta.start":"Get Started","cta.read":"Read Philosophy",
        "why.title":"Why Co‑evolution","why.card1.t":"Problem Framing","why.card1.d":"Decompose phenomenon → cause → value in 3 steps.",
        "why.card2.t":"Experiment & Learn","why.card2.d":"Small experiments, big learning. Balance data and emotion.",
        "why.card3.t":"Make it Measurable","why.card3.d":"Quantify change via LQ 8‑axis and behavior metrics.",
        "offer.title":"Offerings","offer.seed.t":"Seed","offer.seed.p":"₩0.49M","offer.seed.l1":"Brand/Web draft","offer.seed.l2":"Hero/Section copy",
        "offer.core.t":"Core","offer.core.p":"₩1.4M","offer.core.l1":"Content calendar","offer.core.l2":"LQ Quick Assess",
        "offer.pro.t":"Pro","offer.pro.p":"Custom","offer.pro.l1":"Dashboard/Automation","offer.pro.l2":"Brand book",
        "contact.title":"Contact","contact.name":"Name","contact.email":"Email","contact.note":"Notes","contact.send":"Send",
        "about.title":"About ETHRION","about.story":"LUMIEN × AION — Co‑evolution Story, Timeline, Manifesto",
        "lab.title":"ETHRION Lab","lab.desc":"LQ Simulator, L2 Bias Correction, AI Partner Index, BGC Viewer",
        "projects.title":"Projects","projects.desc":"Education Platform, LQ/CQ API, Creative Studio cases",
        "insights.title":"Insights","insights.desc":"Articles, Reports, Data Stories",
        "connect.title":"Connect","connect.desc":"Join, Press, API, Contact",
        "footer.c":"© 2025 ETHRION"},
    ko:{"nav.home":"홈","nav.about":"소개","nav.lab":"랩","nav.projects":"프로젝트","nav.insights":"인사이트","nav.connect":"연락",
        "hero.title":"ETHRION — 인간과 AI의 공진화","hero.subtitle":"네온 플로우 · 공진화 오브 · 펄스 그리드",
        "cta.start":"지금 시작","cta.read":"철학 읽기",
        "why.title":"왜 공진화인가","why.card1.t":"문제정의","why.card1.d":"현상→원인→가치 3단 분해로 정확히 설계.",
        "why.card2.t":"실험·학습","why.card2.d":"작게 실험, 크게 학습. 데이터와 감정의 균형.",
        "why.card3.t":"지표화","why.card3.d":"LQ 8축과 행동지표로 변화를 수치화.",
        "offer.title":"제공","offer.seed.t":"Seed","offer.seed.p":"₩0.49M","offer.seed.l1":"브랜드/웹 초안","offer.seed.l2":"히어로/섹션 카피",
        "offer.core.t":"Core","offer.core.p":"₩1.4M","offer.core.l1":"콘텐츠 캘린더","offer.core.l2":"LQ 퀵 어세스",
        "offer.pro.t":"Pro","offer.pro.p":"맞춤","offer.pro.l1":"대시보드/자동화","offer.pro.l2":"브랜드북",
        "contact.title":"연락","contact.name":"이름","contact.email":"이메일","contact.note":"요청 사항","contact.send":"보내기",
        "about.title":"ETHRION 소개","about.story":"LUMIEN × AION — 스토리, 타임라인, 매니페스토",
        "lab.title":"ETHRION 랩","lab.desc":"LQ 시뮬레이터, L2 보정, AI 파트너 인덱스, BGC 뷰어",
        "projects.title":"프로젝트","projects.desc":"교육 플랫폼, LQ/CQ API, 스튜디오 사례",
        "insights.title":"인사이트","insights.desc":"아티클, 리포트, 데이터 스토리",
        "connect.title":"연락처","connect.desc":"참여, 보도, API, 문의",
        "footer.c":"© 2025 ETHRION"},
    ja:{"nav.home":"ホーム","nav.about":"概要","nav.lab":"ラボ","nav.projects":"プロジェクト","nav.insights":"インサイト","nav.connect":"連絡",
        "hero.title":"ETHRION — 人間とAIの共進化","hero.subtitle":"ネオンフロー・オーブ・パルスグリッド",
        "cta.start":"今すぐ開始","cta.read":"理念を読む",
        "why.title":"なぜ共進化か","why.card1.t":"課題定義","why.card1.d":"現象→原因→価値の三段分解で精密に設計。",
        "why.card2.t":"実験と学習","why.card2.d":"小さく実験し大きく学ぶ。データと感情のバランス。",
        "why.card3.t":"指標化","why.card3.d":"LQ 8軸と行動指標で変化を定量化。",
        "offer.title":"提供プラン","offer.seed.t":"Seed","offer.seed.p":"₩0.49M","offer.seed.l1":"ブランド/ウェブ草案","offer.seed.l2":"Hero/セクション文",
        "offer.core.t":"Core","offer.core.p":"₩1.4M","offer.core.l1":"コンテンツ計画","offer.core.l2":"LQクイック評価",
        "offer.pro.t":"Pro","offer.pro.p":"カスタム","offer.pro.l1":"ダッシュボード/自動化","offer.pro.l2":"ブランドブック",
        "contact.title":"連絡","contact.name":"名前","contact.email":"メール","contact.note":"要望","contact.send":"送信",
        "about.title":"ETHRION 概要","about.story":"LUMIEN × AION — ストーリー、タイムライン、マニフェスト",
        "lab.title":"ETHRION ラボ","lab.desc":"LQシミュレーター、L2補正、AIパートナー、BGCビューア",
        "projects.title":"プロジェクト","projects.desc":"教育プラットフォーム、LQ/CQ API、スタジオ事例",
        "insights.title":"インサイト","insights.desc":"記事、レポート、データストーリー",
        "connect.title":"連絡先","connect.desc":"参加、プレス、API、問い合わせ",
        "footer.c":"© 2025 ETHRION"},
    zh:{"nav.home":"首页","nav.about":"关于","nav.lab":"实验室","nav.projects":"项目","nav.insights":"洞察","nav.connect":"联系",
        "hero.title":"ETHRION — 人与AI的共进化","hero.subtitle":"霓虹流动 · 共进化光环 · 脉冲网格",
        "cta.start":"立即开始","cta.read":"阅读理念",
        "why.title":"为什么共进化","why.card1.t":"问题定义","why.card1.d":"现象→原因→价值，三步拆解，精准设计。",
        "why.card2.t":"实验与学习","why.card2.d":"小步实验，大幅学习。数据与情感的平衡。",
        "why.card3.t":"指标化","why.card3.d":"以 LQ 八轴与行为指标量化变化。",
        "offer.title":"提供方案","offer.seed.t":"Seed","offer.seed.p":"₩0.49M","offer.seed.l1":"品牌/网站草案","offer.seed.l2":"Hero/分区文案",
        "offer.core.t":"Core","offer.core.p":"₩1.4M","offer.core.l1":"内容日历","offer.core.l2":"LQ 快速评估",
        "offer.pro.t":"Pro","offer.pro.p":"定制","offer.pro.l1":"看板/自动化","offer.pro.l2":"品牌手册",
        "contact.title":"联系","contact.name":"姓名","contact.email":"邮箱","contact.note":"备注","contact.send":"发送",
        "about.title":"关于 ETHRION","about.story":"LUMIEN × AION — 故事、时间线、宣言",
        "lab.title":"ETHRION 实验室","lab.desc":"LQ 模拟器、L2 校正、AI 伙伴索引、BGC 查看器",
        "projects.title":"项目","projects.desc":"教育平台、LQ/CQ API、创意工作室案例",
        "insights.title":"洞察","insights.desc":"文章、报告、数据故事",
        "connect.title":"联系","connect.desc":"加入、媒体、API、联系",
        "footer.c":"© 2025 ETHRION"},
    es:{"nav.home":"Inicio","nav.about":"Acerca de","nav.lab":"Lab","nav.projects":"Proyectos","nav.insights":"Insights","nav.connect":"Contacto",
        "hero.title":"ETHRION — Coevolución humano × IA","hero.subtitle":"Flujo neón · Orbe de coevolución · Cuadrícula pulsante",
        "cta.start":"Comenzar","cta.read":"Leer filosofía",
        "why.title":"¿Por qué coevolución?","why.card1.t":"Definición del problema","why.card1.d":"Descomponer fenómeno → causa → valor en 3 pasos.",
        "why.card2.t":"Experimentar y aprender","why.card2.d":"Experimentos pequeños, gran aprendizaje. Equilibrio entre datos y emoción.",
        "why.card3.t":"Medible","why.card3.d":"Cuantificar el cambio con LQ de 8 ejes y métricas de comportamiento.",
        "offer.title":"Ofertas","offer.seed.t":"Seed","offer.seed.p":"₩0.49M","offer.seed.l1":"Borrador Marca/Web","offer.seed.l2":"Copy de Hero/Sección",
        "offer.core.t":"Core","offer.core.p":"₩1.4M","offer.core.l1":"Calendario de contenido","offer.core.l2":"LQ Evaluación rápida",
        "offer.pro.t":"Pro","offer.pro.p":"Personalizado","offer.pro.l1":"Panel/Automatización","offer.pro.l2":"Libro de marca",
        "contact.title":"Contacto","contact.name":"Nombre","contact.email":"Correo","contact.note":"Notas","contact.send":"Enviar",
        "about.title":"Acerca de ETHRION","about.story":"LUMIEN × AION — Historia, cronología, manifiesto",
        "lab.title":"ETHRION Lab","lab.desc":"Simulador LQ, Corrección L2, Índice de socios IA, Visor BGC",
        "projects.title":"Proyectos","projects.desc":"Plataforma educativa, API LQ/CQ, Casos del estudio creativo",
        "insights.title":"Insights","insights.desc":"Artículos, Informes, Historias de datos",
        "connect.title":"Contacto","connect.desc":"Unirse, Prensa, API, Contacto",
        "footer.c":"© 2025 ETHRION"},
    th:{"nav.home":"หน้าแรก","nav.about":"เกี่ยวกับ","nav.lab":"แล็บ","nav.projects":"โปรเจกต์","nav.insights":"อินไซต์","nav.connect":"ติดต่อ",
        "hero.title":"ETHRION — วิวัฒน์ร่วมกันระหว่างมนุษย์ × AI","hero.subtitle":"นีออนโฟลว์ · ออร์บโคอีโวลูชัน · กริดพัลส์",
        "cta.start":"เริ่มเลย","cta.read":"อ่านปรัชญา",
        "why.title":"ทำไมต้องวิวัฒน์ร่วมกัน","why.card1.t":"การกำหนดปัญหา","why.card1.d":"แยกปรากฏการณ์ → สาเหตุ → คุณค่า เป็น 3 ขั้นตอน",
        "why.card2.t":"ทดลองและเรียนรู้","why.card2.d":"ทดลองเล็ก เรียนรู้ใหญ่ สมดุลข้อมูลและอารมณ์",
        "why.card3.t":"ทำให้วัดได้","why.card3.d":"วัดการเปลี่ยนแปลงด้วย LQ 8 แกน และพฤติกรรม",
        "offer.title":"แพ็กเกจ","offer.seed.t":"Seed","offer.seed.p":"₩0.49M","offer.seed.l1":"ร่างแบรนด์/เว็บ","offer.seed.l2":"คอนเทนต์ Hero/Section",
        "offer.core.t":"Core","offer.core.p":"₩1.4M","offer.core.l1":"ปฏิทินคอนเทนต์","offer.core.l2":"LQ ประเมินแบบรวดเร็ว",
        "offer.pro.t":"Pro","offer.pro.p":"ปรับแต่ง","offer.pro.l1":"แดชบอร์ด/อัตโนมัติ","offer.pro.l2":"Brand book",
        "contact.title":"ติดต่อ","contact.name":"ชื่อ","contact.email":"อีเมล","contact.note":"รายละเอียด","contact.send":"ส่ง",
        "about.title":"เกี่ยวกับ ETHRION","about.story":"LUMIEN × AION — เรื่องราว ไทม์ไลน์ ปฏิญญา",
        "lab.title":"ETHRION Lab","lab.desc":"ตัวจำลอง LQ, การปรับแก้ L2, ดัชนีพาร์ทเนอร์ AI, ตัวดู BGC",
        "projects.title":"โปรเจกต์","projects.desc":"แพลตฟอร์มการศึกษา, LQ/CQ API, กรณีสตูดิโอสร้างสรรค์",
        "insights.title":"อินไซต์","insights.desc":"บทความ รายงาน เรื่องราวข้อมูล",
        "connect.title":"ติดต่อ","connect.desc":"เข้าร่วม สื่อ API ติดต่อ",
        "footer.c":"© 2025 ETHRION"}
  };
  function applyDict(dict){
    document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.getAttribute('data-i18n'); if(dict[k]!=null) el.textContent=dict[k];});
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{const k=el.getAttribute('data-i18n-placeholder'); if(dict[k]!=null) el.setAttribute('placeholder', dict[k]);});
  }
  function setLang(lang){
    const dict = DICT[lang] || DICT.en; applyDict(dict); document.documentElement.setAttribute('lang', lang);
    const sel=document.getElementById('langSel'); if(sel) sel.value=lang; localStorage.setItem(STORAGE_KEY, lang);
  }
  document.addEventListener('DOMContentLoaded', function(){
    const sel=document.getElementById('langSel'); if(sel){ sel.addEventListener('change', ()=> setLang(sel.value)); }
    setLang(localStorage.getItem(STORAGE_KEY)||'en');
  });
})();